[package]
name = "canister"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.75"
candid = { version = "0.9.1", features = ["parser"] }
ic-cdk-timers = "0.4.0"
ic-stable-structures = "0.6.0"
canister_methods = { path = "../canister_methods" }
slotmap = "=1.0.6"
ic-cdk = "0.10.0"
ic-cdk-macros = "0.7.0"
ic-wasi-polyfill = { git = "https://github.com/wasm-forge/ic-wasi-polyfill", rev = "1693665ed57adc4f997a0313555ec0b0b5de1c07" }
wasmedge_quickjs = { git = "https://github.com/demergent-labs/wasmedge-quickjs", rev = "09edab8fbfa15e17f91d834003589fc7e60357ba" }
# wasmedge_quickjs = { path = "/home/wasmedge-quickjs" }
