[package]
name = "canister"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
experimental = []

[dependencies]
anyhow = "1.0.75"
ic-cdk = "0.12.1"
ic-cdk-macros = "0.8.4"
ic-cdk-timers = "0.6.0"
candid = "0.10.2"
candid_parser = "0.1.2"
ic-stable-structures = "0.6.5"
open_value_sharing = { path = "../open_value_sharing" }
slotmap = "=1.0.6"
wasmi = "0.31.2"
sha2 = "0.10.8"
serde = "1.0.202"
serde_json = "1.0.107"

ic-wasi-polyfill = "0.5.0"

wasmedge_quickjs = { git = "https://github.com/demergent-labs/wasmedge-quickjs", rev = "573c6c07316de64e4bb9a9561b079f265fd9bcc4" }
# wasmedge_quickjs = { path = "/home/wasmedge-quickjs" }
